//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipTree.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipTree.Resources.Dialog", typeof(Dialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This row color definition already exists..
        /// </summary>
        internal static string AddColorCopiedFromColorAlreadyExists {
            get {
                return ResourceManager.GetString("AddColorCopiedFromColorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value for &quot;Row Color&quot;..
        /// </summary>
        internal static string AddColorNoRowColorSelected {
            get {
                return ResourceManager.GetString("AddColorNoRowColorSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value for &quot;Text Color&quot;..
        /// </summary>
        internal static string AddColorNoTextColorSelected {
            get {
                return ResourceManager.GetString("AddColorNoTextColorSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number of days..
        /// </summary>
        internal static string CleanNoValidValueForDaysEntered {
            get {
                return ResourceManager.GetString("CleanNoValidValueForDaysEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Files (*.html)|*.html.
        /// </summary>
        internal static string HTMLFilesFilter {
            get {
                return ResourceManager.GetString("HTMLFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exists..
        /// </summary>
        internal static string NameAlreadyExists {
            get {
                return ResourceManager.GetString("NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value for &quot;Copied From&quot;..
        /// </summary>
        internal static string NoCopiedFromEntered {
            get {
                return ResourceManager.GetString("NoCopiedFromEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates are currently available..
        /// </summary>
        internal static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open List.
        /// </summary>
        internal static string OpenClipboardHistory {
            get {
                return ResourceManager.GetString("OpenClipboardHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text Files (*.rtf)|*.rtf.
        /// </summary>
        internal static string RichTextFilesFilter {
            get {
                return ResourceManager.GetString("RichTextFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule definition already exists..
        /// </summary>
        internal static string RuleAlreadyExists {
            get {
                return ResourceManager.GetString("RuleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save List As.
        /// </summary>
        internal static string SaveHistoryListTItle {
            get {
                return ResourceManager.GetString("SaveHistoryListTItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Item As.
        /// </summary>
        internal static string SaveListItem {
            get {
                return ResourceManager.GetString("SaveListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (*.xml)|*.xml.
        /// </summary>
        internal static string SupportFileFilter {
            get {
                return ResourceManager.GetString("SupportFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt)|*.txt.
        /// </summary>
        internal static string TextFilesFilter {
            get {
                return ResourceManager.GetString("TextFilesFilter", resourceCulture);
            }
        }
    }
}
